title: Bing's Blog
lang: en
description: Look the world on the code.

## local method ##
theme: jekyll-rtd-theme
debug:
  compress: false
  dist: true
  shortcodes: true

## remote method ##
# remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions